[package]
name = "bitcoin-coin-selection-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rand = "0.8.5"
bitcoin = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "2ee9c3c6638320af0af4e65584bcdb5468a9be8c", features = ["arbitrary"] }
arbitrary = { version = "1", features = ["derive"] }

[dependencies.bitcoin-coin-selection]
path = ".."
features = ["rand"]

[[bin]]
name = "select_coins_srd"
path = "fuzz_targets/select_coins_srd.rs"
test = false
doc = false
bench = false

[[bin]]
name = "select_coins_bnb"
path = "fuzz_targets/select_coins_bnb.rs"
test = false
doc = false
bench = false

[[bin]]
name = "select_coins"
path = "fuzz_targets/select_coins.rs"
test = false
doc = false
bench = false

[patch.crates-io]
bitcoin_hashes = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "2ee9c3c6638320af0af4e65584bcdb5468a9be8c" }
base58ck = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "2ee9c3c6638320af0af4e65584bcdb5468a9be8c" }
bitcoin-internals = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "2ee9c3c6638320af0af4e65584bcdb5468a9be8c" }
bitcoin-io = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "2ee9c3c6638320af0af4e65584bcdb5468a9be8c" }
bitcoin-primitives = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "2ee9c3c6638320af0af4e65584bcdb5468a9be8c" }
bitcoin-addresses = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "2ee9c3c6638320af0af4e65584bcdb5468a9be8c" }
bitcoin-units = { git = "https://github.com/rust-bitcoin/rust-bitcoin.git", rev = "2ee9c3c6638320af0af4e65584bcdb5468a9be8c" }
