on: [push, pull_request]

name: Continuous integration

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: stable
            env:
              DO_COV: true
              DO_LINT: true
              AS_DEPENDENCY: true
              DO_NO_STD: true
              DO_FEATURE_MATRIX: true # Currently only used in hashes crate.
              DO_SCHEMARS_TESTS: true # Currently only used in hashes crate.
          - rust: beta
            env:
              AS_DEPENDENCY: true
              DO_NO_STD: true
          - rust: nightly
            env:
              DO_BENCH: true
              AS_DEPENDENCY: true
              DO_NO_STD: true
              DO_DOCS: true
          - rust: 1.41.1
            env:
              AS_DEPENDENCY: true
          - rust: 1.47
            env:
              AS_DEPENDENCY: true
              DO_NO_STD: true
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Running test script
        env: ${{ matrix.env }}
        run: ./contrib/test.sh
